apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piyasa-monitoring

resources:
  # Namespace
  - monitoring-namespace.yaml

  # Prometheus
  - prometheus-configmap.yaml
  - prometheus-rules-configmap.yaml
  - prometheus-deployment.yaml

  # AlertManager
  - alertmanager-configmap.yaml
  - alertmanager-deployment.yaml

  # Grafana
  - grafana-configmap.yaml
  - grafana-dashboard-configmap.yaml
  - grafana-deployment.yaml

commonLabels:
  project: piyasa-chatbot
  component: monitoring
